export const INITIALIZE_SIGNUP = 'INITIALIZE_SIGNUP'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'




export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'



export const FETCH_TODOS_INIT = "FETCH_TODOS_INIT"
export const FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS"
export const FETCH_TODOS_FAIL = "FETCH_TODOS_FAIL"


export const NEW_TODO_INIT = "NEW_TODO_INIT"
export const NEW_TODO_SUCCESS = "NEW_TODO_SUCCESS"
export const NEW_TODO_FAIL = "NEW_TODO_FAIL"